# Install build dependencies for the right architecture per target
# [target.i686-unknown-linux-gnu]
# runner = "qemu-user" 
# pre-build = [
#   "export BUILDKIT_PROGRESS=plain",
#   "dpkg --add-architecture $CROSS_DEB_ARCH", 
#   "apt-get update && apt-get --assume-yes install libasound2-dev:$CROSS_DEB_ARCH libjack-jackd2-dev:$CROSS_DEB_ARCH" 
# ]

[target.aarch64-unknown-linux-gnu]
runner = "qemu-user" 
pre-build = [
  "export BUILDKIT_PROGRESS=plain",
  "dpkg --add-architecture $CROSS_DEB_ARCH", 
  "apt-get update && apt-get --assume-yes install libasound2-dev:$CROSS_DEB_ARCH libjack-jackd2-dev:$CROSS_DEB_ARCH" 
]

[target.armv7-unknown-linux-gnueabihf]
runner = "qemu-user" 
pre-build = [
  "export BUILDKIT_PROGRESS=plain",
  "dpkg --add-architecture $CROSS_DEB_ARCH", 
  "apt-get update && apt-get --assume-yes install libasound2-dev:$CROSS_DEB_ARCH libjack-jackd2-dev:$CROSS_DEB_ARCH" 
]

